version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad
    ports:
      - "9001:9001"
    environment:
      AUTHENTICATION_METHOD: "apikey"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  api:
    build: ./api
    image: bigchef/tlc-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

  front:
    build: ./front
    image: bigchef/tlc-frontend:latest
    ports:
      - "4200:80"
    depends_on:
      - api