services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad
    ports:
      - "9001:9001"
    environment:
      AUTHENTICATION_METHOD: "apikey"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  api:
    build: ./api
    image: bigchef/tlc-backend:latest
    ports:
      - "8080:8080"
    environment:
      - PAD_EXTERNAL_URL=http://etherpad:9001/
    depends_on:
      - db

  front:
    build: ./front
    image: bigchef/tlc-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
 
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/quarkus-dashboard.json
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "certbot renew --quiet --webroot -w /var/www/certbot && while :; do sleep 86400; certbot renew --quiet --webroot -w /var/www/certbot; done"
    depends_on:
      - front
    restart: always