services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://db:3306/tlc
      - QUARKUS_DATASOURCE_USERNAME=tlc
      - QUARKUS_DATASOURCE_PASSWORD=tlc
      - QUARKUS_DATASOURCE_DEVSERVICES_ENABLED=false
    depends_on:
      - db
      - etherpad
      - mail
      
    restart: on-failure